services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: checkmo_db
      MYSQL_ROOT_PASSWORD: checkmo123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - checkmo-network

networks:
  checkmo-network:
    driver: bridge

volumes:
  mysql_data: