services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: checkmo_db
      MYSQL_ROOT_PASSWORD: checkmo123
    ports:
      - '3309:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - checkmo-network

networks:
  checkmo-network:
    driver: bridge

volumes:
  mysql_data: