services:
  app:
    image: nginx #ecr 주소 추가 예정 (지금은 아무거나 넣어놓음)
    container_name: checkmo
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped