services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: checkmo_db
      MYSQL_ROOT_PASSWORD: checkmo123
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  checkmo-network:
    driver: bridge

volumes:
  mysql_data: