services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: checkmo_db
      MYSQL_ROOT_PASSWORD: checkmo123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - checkmo-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  redis:
    image: 'redis:7.2-alpine'
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass checkmo123
    volumes:
      - redis_data:/data
    networks:
      - checkmo-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "checkmo123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  checkmo-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: