spring:
  profiles:
    include:
      - prod
      - redis
      - aladin
      - mail
      - jwt
      - oauth2
      - s3
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
      completion-mode: DELETE

server:
  forward-headers-strategy: NATIVE