spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: checkmo123
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false