spring:
  datasource:
    url: jdbc:mysql://localhost:3307/checkmo_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: checkmo123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop