server:
  forward-headers-strategy: framework

app:
  oauth2:
    redirect:
      base-uri: ${FRONTEND_BASE_URI}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://api.checkmo.co.kr/login/oauth2/code/google"
            authorization-grant-type: authorization_code

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - profile_nickname
            redirect-uri: "https://api.checkmo.co.kr/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email
            redirect-uri: "https://api.checkmo.co.kr/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver