spring:
  profiles:
    include:
      - prod
      - redis
      - aladin
      - mail
      - jwt
      - oauth2
      - s3
      - flyway
  modulith:
    events:
      completion-mode: DELETE

server:
  forward-headers-strategy: NATIVE