spring:
  datasource:
    url: jdbc:mysql://${DOCKER_MYSQL_HOST}:${DOCKER_MYSQL_PORT}/${DOCKER_MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  docker:
    compose:
      enabled: true
      file: compose-dev.yaml
      lifecycle-management: start_and_stop