package checkmo.clubManagement.internal.entity;

public enum ClubInterestCategory {
    DOMESTIC,
    FICTION_POETRY_DRAMA,
    ESSAY,
    ECONOMY_MANAGEMENT,
    SELF_DEVELOPMENT,
    HUMANITIES,
    TRAVEL,
    HISTORY_CULTURE,
    SOCIAL_SCIENCE,
    POLITICS_DIPLOMACY_DEFENSE,
    COMPUTER_IT,
    SCIENCE,
    FOREIGN_LANGUAGE,
    ART_POP_CULTURE,
    CHILDREN
}
