server {
    listen 80;
    server_name checkmo.shop;

    location / {
        proxy_pass http://backend;

        include /etc/nginx/conf.d/snippets/proxy-settings.conf;
        include /etc/nginx/conf.d/snippets/cors-settings.conf;
    }

    include /etc/nginx/conf.d/snippets/security-headers.conf;
}