CREATE TABLE IF NOT EXISTS team_chat_message (
    id BIGINT NOT NULL AUTO_INCREMENT,

    club_id BIGINT NOT NULL,
    meeting_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,

    sender_member_id VARCHAR(255) NOT NULL,

    content TEXT NOT NULL,
    sent_at DATETIME(6) NOT NULL,

    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB;